---
date: 2022-11-14
lesson: Stat5
thema: Von linearen Modellen zu GLMMs
index: 2
---

# Stat5: Übung

## Aufgabe 5.1: Split-plot ANOVA

**Datensatz [splityield.csv](https://raw.githubusercontent.com/ResearchMethods-ZHAW/datasets/main/statistik/splityield.csv)**

Versuch zum Ernteertrag (yield) einer Kulturpflanze in Abhängigkeit der drei Faktoren Bewässerung (irrigated vs. control), Düngung (N, NP, P) und Aussaatdichten (low, medium, high). Es gab vier ganze Felder (block), die zwei Hälften mit den beiden Bewässerungstreatments, diese wiederum drei Drittel für die drei Saatdichten und diese schliesslich je drei Drittel für die drei Düngertreatments hatten.

### Aufgaben

- Bestimmt das minimal adäquate Modell
- Stellt die Ergebnisse da

## Aufgabe 5.2: GLMM

Führt mit dem Datensatz [novanimal.csv](https://zenodo.org/record/3890949/files/2017_ZHAW_individual_menu_sales_NOVANIMAL.csv?download=1) eine logistische Regression durch, wobei ihr die einzelnen Käufer (single campus_card holder) als weitere randomisierte Variable mitberücksichtigt. Kann der Fleischkonsum durch das Geschlecht, die Hochschulzugehörigkeit und das Alter erklärt werden? Vergleich die Ergebnisse mit der eurem multiplen logistische Modell von Aufgabe 4.2.

**Kann der Fleischkonsum nun besser durch das Geschlecht, die Hochschulzugehörigkeit und das Alter erklärt werden?**

### Aufgaben

- Bestimmt das minimal adäquate Modell
- Stellt die Ergebnisse dar

Ähnliches Vorgehen wie bei der Übung 4.2S:

-   Generiert eine neue Variable "Fleisch" (0 = kein Fleisch, 1 = Fleisch)
-   Entfernt fehlende Werte aus der Variable "Fleisch"
-   Lasst für die Analyse den Menüinhalt "Buffet" weg
