project: 
  type: book
  preview: 
      port: 5678
  execute-dir: project

format: 
  html:
    toc: true
    theme: flatly
    bibliography: bibliography.bib
    number-sections: false
    code-tools: true
    
execute:
  freeze: false   
    
book:
  title: "Research Methods"
  repo-url: https://github.com/ResearchMethods-ZHAW/HS22/
  site-url: https://researchmethods-zhaw.github.io/HS22/
  sidebar: 
    collapse-level: 1
    style: docked
  chapters:
    - index.qmd
    - part: "Prepro"
      chapters:
      - prepro/Prepro1_Demo.qmd
      - prepro/Prepro1_Uebung.qmd
      - --
      - prepro/Prepro2_Demo.qmd
      - prepro/Prepro2_Uebung_A.qmd
      - prepro/Prepro2_Uebung_B.qmd
      - --
      - prepro/Prepro3_Demo.qmd
      - prepro/Prepro3_Uebung.qmd
    - part: "InfoVis"
      chapters:
      - infovis/Infovis1_Demo.qmd
      - infovis/Infovis1_Script_eda.qmd
      - infovis/Infovis1_Uebung.qmd
      - --
      - infovis/Infovis2_cairo_wheel.qmd
      - infovis/Infovis2_Uebung_A.qmd
      - infovis/Infovis2_Uebung_B.qmd
    - part: "Stat1-4"
      chapters:
      - stat1-4/Statistik1_Demo.qmd
      - stat1-4/Statistik1_Loesung.qmd
      - stat1-4/Statistik1_Novanimal.qmd
      - stat1-4/Statistik1_Uebung.qmd
      - --
      - stat1-4/Statistik2_Demo.qmd
      - stat1-4/Statistik2_Loesung_1.qmd
      - stat1-4/Statistik2_Loesung_2223s.qmd
      - stat1-4/Statistik2_Loesung_23n.qmd
      - stat1-4/Statistik2_Loesung_Beispiel.qmd
      - stat1-4/Statistik2_Uebung.qmd
      - --
      - stat1-4/Statistik3_Demo.qmd
      - stat1-4/Statistik3_Loesung.qmd
      - stat1-4/Statistik3_Uebung.qmd
      - --
      - stat1-4/Statistik4_Demo.qmd
      - stat1-4/Statistik4_Loesung_1.qmd
      - stat1-4/Statistik4_Loesung_2n.qmd
      - stat1-4/Statistik4_Loesung_2s.qmd
      - stat1-4/Statistik4_Uebung.qmd
    - part: "Stat5-8"
      chapters:
      - stat5-8/Statistik5_Demo.qmd
      - stat5-8/Statistik5_Loesung_1.qmd
      - stat5-8/Statistik5_Loesung_2.qmd
      - stat5-8/Statistik5_Uebung.qmd
      - --
      - stat5-8/Statistik6_Demo.qmd
      - stat5-8/Statistik6_Loesung.qmd
      - stat5-8/Statistik6_Uebung.qmd
      - --
      - stat5-8/Statistik7_Demo.qmd
      - stat5-8/Statistik7_Loesung.qmd
      - stat5-8/Statistik7_Uebung.qmd
      - --
      - stat5-8/Statistik8_Demo.qmd
      - stat5-8/Statistik8_Loesung.qmd
      - stat5-8/Statistik8_Uebung.qmd
    - part: "StatKons"
      chapters:
      - statKons/StatKons1_Demo_assoziationen.qmd
      - statKons/StatKons1_Demo_open_datasets.qmd
      - statKons/StatKons1_Demo_suggest_datasets.qmd
      - --
      - statKons/StatKons2_Demo_PCA.qmd
      - --
      - statKons/StatKons3_Demo_LM.qmd
      - --
      - statKons/StatKons4_Demo_GLM.qmd
    - part: "Rauman"
      chapters:
      - rauman/Rauman1_Uebung_A.qmd
      - rauman/Rauman1_Uebung_B.qmd
      - --
      - rauman/Rauman2_Uebung_A.qmd
      - rauman/Rauman2_Uebung_B.qmd
      - rauman/Rauman2_Uebung_C.qmd
      - --
      - rauman/Rauman3_Uebung_A.qmd
      - --
      - rauman/Rauman4_Uebung_A_ahp.qmd
      - rauman/Rauman4_Uebung_B_raster.qmd
      - --
      - rauman/Rauman5_Uebung_mce.qmd 