project: 
  type: website
  render:
    - index.qmd
    - prepro/**
    - infovis/*
    - rauman/*
    - PrePro.qmd
    - InfoVis.qmd
  preview: 
      port: 5678
    
website:
  title: "Modul Research Methods"
  repo-url: https://github.com/ResearchMethods-ZHAW/HS22/
  site-url: https://researchmethods-zhaw.github.io/HS22/
  navbar:
    logo: images/zhaw_sw_neg.png
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Prepro"
        file: PrePro.qmd
      - text: InfoViz
        file: InfoVis.qmd
#        - text: "Abstract"
#          file: prepro/PrePro_abstract.qmd
#        - text: "---"
#        - text: "PrePro1"
#          file: prepro/PrePro.qmd#category=PrePro1
#        - text: "PrePro2"
#          file: prepro/PrePro.qmd#category=PrePro2  
#        - text: "PrePro3"
#          file: prepro/PrePro.qmd#category=PrePro3
#      - text: "InfoVis"
#        menu:
#        - text: "Abstract"
#          href: infovis/InfoVis_abstract.qmd
#        - text: "---"
#        - text: "InfoVis1"
#          href: infovis/InfoVis.qmd#category=InfoVis1
#        - text: "InfoVis2"
#          href: infovis/InfoVis.qmd#category=InfoVis2
#      - text: "Statistik"
#        menu:
#        - text: "Abstract"
#          href: statistik/Statistik_abstract.qmd
#        - text: "---"
#        - text: "Statistik 1 - 4"
#        - text: "Statistik1"
#          href: statistik/Statistik.qmd#category=Statistik1
#        - text: "Statistik2"
#          href: statistik/Statistik.qmd#category=Statistik2
#        - text: "Statistik3"
#          href: statistik/Statistik.qmd#category=Statistik3
#        - text: "Statistik4"
#          href: statistik/Statistik.qmd#category=Statistik4
#        - text: "---"
#        - text: "Statistik 5 - 8"
#        - text: "Statistik5"
#          href: statistik/Statistik.qmd#category=Statistik5
#        - text: "Statistik6"
#          href: statistik/Statistik.qmd#category=Statistik6
#        - text: "Statistik7"
#          href: statistik/Statistik.qmd#category=Statistik7
#        - text: "Statistik8"
#          href: statistik/Statistik.qmd#category=Statistik8
#      - text: "Statistik Konsolidierung"
#        menu:
#        - text: "Abstract"
#          href: statistik-konsolidierung/Statistik-Konsolidierung_abstract.qmd
#        - text: "---"
#        - text: "Statistik Konsolidierung 1 - 4"
#        - text: "Statistik_Konsolidierung1"
#          href: statistik-konsolidierung/Statistik-Konsolidierung.qmd#category=Statistik_Konsolidierung1
#        - text: "Statistik_Konsolidierung2"
#          href: statistik-konsolidierung/Statistik-Konsolidierung.qmd#category=Statistik_Konsolidierung2
#        - text: "Statistik_Konsolidierung3"
#          href: statistik-konsolidierung/Statistik-Konsolidierung.qmd#category=Statistik_Konsolidierung3
#        - text: "Statistik_Konsolidierung4"
#          href: statistik-konsolidierung/Statistik-Konsolidierung.qmd#category=Statistik_Konsolidierung4
#      - text: "Räumliche Analyse"
#        menu:
#        - text: "Abstract"
#          href: rauman/RaumAn_abstract.qmd
#        - text: "---"
#        - text: "RaumAn1"
#          href: rauman/RaumAn.qmd#category=RaumAn1
#        - text: "RaumAn2"
#          href: rauman/RaumAn.qmd#category=RaumAn2
#        - text: "RaumAn3"
#          href: rauman/RaumAn.qmd#category=RaumAn3
#        - text: "RaumAn4"
#          href: rauman/RaumAn.qmd#category=RaumAn4
#        - text: "RaumAn5"
#          href: rauman/RaumAn.qmd#category=RaumAn5
#      - text: "Fallstudien"
#        menu:
#        - text: "Biodiversity and Ecosystems (Profil S)"
#          href: fallstudien/Fallstudien.qmd#category=Biodiversity_Ecosystems_N
#        - text: "Biodiversity and Ecosystems (Profil S): Musterlösung"
#          href: fallstudien/Fallstudien.qmd#category=Biodiversity_Ecosystems_S_Musterloesung
#        - text: "Biodiversity and Ecosystems (Profil N)"
#          href: fallstudien/Fallstudien.qmd#category=Biodiversity_Ecosystems_N
#        - text: "Biodiversity and Ecosystems (Profil N): Musterlösung"
#          href: fallstudien/Fallstudien.qmd#category=Biodiversity_Ecosystems_N_Musterloesung    
#    right:
#      - text: "Interna"
#        menu:
#        - text: "README"
#          href: README.qmd
#        - icon: github
#          href: https://github.com/ResearchMethods-ZHAW/HS22

format: 
  html:
    toc: true
    theme: flatly
    scss: mystyle.scss
    include-after-body: _footer.html
    bibliography: bibliography.bib
    
execute:
  freeze: auto    