project: 
  type: book
  render:
    - index.qmd
    - prepro/**
    - infovis/*
    - rauman/*
    - stat1-4/*
    - stat5-8/*
    - statKons/*
    - PrePro.qmd
    - InfoVis.qmd
    - RaumAn.qmd
    - Stat1-4.qmd
    - Stat5-8.qmd
    - StatKons.qmd
  preview: 
      port: 5678
    
book:
  title: "Modul Research Methods"
  repo-url: https://github.com/ResearchMethods-ZHAW/HS22/
  site-url: https://researchmethods-zhaw.github.io/HS22/
  sidebar: 
    collapse-level: 1
  chapters:
    - index.qmd
    - part: PrePro.qmd
      chapters:
      - prepro/Prepro1_Demo.qmd
      - prepro/Prepro1_Uebung.qmd
      - prepro/Prepro2_Demo.qmd
      - prepro/Prepro2_Uebung_A.qmd
      - prepro/Prepro2_Uebung_B.qmd
      - prepro/Prepro3_Demo.qmd
      - prepro/Prepro3_Uebung.qmd
    - part: InfoVis.qmd
      chapters:
      - infovis/Infovis1_Demo.qmd
      - infovis/Infovis1_Script_eda.qmd
      - infovis/Infovis2_cairo_wheel.qmd
      - infovis/Infovis1_Uebung.qmd
      - infovis/Infovis2_Uebung_A.qmd
      - infovis/Infovis2_Uebung_B.qmd



format: 
  html:
    toc: true
    theme: flatly
    scss: mystyle.scss
    include-after-body: _footer.html
    bibliography: bibliography.bib
    
execute:
  freeze: auto    