{
  "hash": "b90d35471a459f3e469e10afefd303c4",
  "result": {
    "markdown": "---\ntitle: \"Lösung\"\nauthor: Gian-Andrea Egeler\nimage: distill-preview.png  \ndescription: \" \"\ncategories: Statistik1\ndraft: false\n---\n\n::: {.cell}\n\n:::\n\n\n#  Musterlösung Übung 1.1\n\n> Download [R-Skript](Statistik1_Loesung.R)\n\n## kommentierter Weg\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Als eine Möglichkeit, die Aufgabe 1.1 zu bearbeiten, nehmen wir hier den \n# Datensatz  der Gästebefragung NOVANIMAL und gehen der folgenden Frage nach: \n# Gibt es einen Zusammenhang zwischen Geschlecht und dem wahrgenommenen \n# Milchkonsum (viel vs. wenig Milch/-produkte)\n\n# die Variable wahrgenommener Milchkonsum muss \n# noch in 2 Kategorien zusammengefasst werden: geringer vs. hoher Milchkonsum\n\n# Variable  milk == wahrgenommener Milchkonsum \n# alles kleiner als 4 (3 inklusive) == geringer wahrgenommener Milchkonsum, \n#alles grösser als 3 (4 inklusive) == hoher wahrgenommener Milchkonsum\nnova2 <- nova_survey %>% \n  filter(gender != \"x\") %>% # x aus der Variable Geschlecht entfernen \n  mutate(milkcon = if_else(milk <= 3, \"wenig\", \"viel\")) %>% \n  select(gender, milkcon) %>% \n  drop_na() # alle Missings können gestrichen werden\n \n# mal anschauen\ntable(nova2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      milkcon\ngender viel wenig\n  Frau  428    64\n  Mann  580    68\n```\n:::\n\n```{.r .cell-code}\n#achtung chi_squre erwartet matrix\nnova_mtx <- xtabs(~ gender + milkcon ,data = nova2) \n# da es in diesem fall keine kriteriumsvariable gibt, fehlt das y sozusagen\n\n#Chi-squared Test\nchi_sq <- chisq.test(nova_mtx)\nchi_sq\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  nova_mtx\nX-squared = 1.49, df = 1, p-value = 0.2222\n```\n:::\n\n```{.r .cell-code}\n#visualisierung\nOP <- par(mfrow=c(1,2), \"mar\"=c(1,1,3,1))\nmosaicplot(chi_sq$observed, cex.axis =1 , main = \"Observed counts\")\nmosaicplot(chi_sq$expected, cex.axis =1 , main = \"Expected counts\\n(wenn geschlecht keinen einfluss hat)\")\n```\n\n::: {.cell-output-display}\n![](Statistik1_Loesung_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(OP)\n\n#Fisher's Test nur mit 2X2 Kontingenztabelle möglich\nfisher.test(nova_mtx)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  nova_mtx\np-value = 0.1922\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n 0.536215 1.147939\nsample estimates:\nodds ratio \n 0.7842283 \n```\n:::\n:::\n\n\n## Ergebnisse\n\nDer $\\chi^2$-Test sagt uns, dass das Geschlecht und der wahrgenommene Milchkonsum nicht zusammenhängen. Es gibt keine signifikante Unterscheide zwischen dem Geschlecht und dem wahrgenommenen Milchkonsum ($\\chi^2$(1) = 1.49, *p* = 0.222. Es sieht so aus, dass Männer leicht mehr angeben weniger Milch zu konsumieren (Tabelle 1). Die Ergebnisse müssen jedoch mit Vorsicht interpretiert werden, denn der $\\chi^2$-Test gibt uns nur an, dass ein signifikanter Unterschied zwischen Geschlecht und wahrgenommener Milchkonsum vorliegt. Um die Unterschiede innerhalb einer Gruppen (z.B. Geschlecht nach Alter) festzustellen bedarf es weiterer Analysen z. B. mit einer mehrfaktorieller ANOVA mit anschliessenden Post-hoc Tests (siehe Statistik 3).\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'gender'. You can override using the\n`.groups` argument.\n```\n:::\n\n::: {.cell-output-display}\nTable: Wahrgenommener Milchkonsum nach Geschlecht\n\n|Geschlecht |wahr. Milchkonsum | absolute Werte| wahr. Milchkonsum (%)|\n|:----------|:-----------------|--------------:|---------------------:|\n|Frau       |viel              |            428|                  87.0|\n|Frau       |wenig             |             64|                  13.0|\n|Mann       |viel              |            580|                  89.5|\n|Mann       |wenig             |             68|                  10.5|\n:::\n:::\n\n\n#  Musterlösung Übung 1.2: t-Test\n\n> Leseempfehlung Kapitel 2 von [Manny Gimond](https://mgimond.github.io/Stats-in-R/z_t_tests.html) \n\n**Null- und Alternativhypothese**\n\n$H_0$: Es gibt keine Unterschiede in den Verkaufszahlen zwischen Basis- und Interventionswochen. \n\n$H_1$: Es gibt Unterschiede in den Verkaufszahlen zwischen Basis- und Interventionswochen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Gemäss Aufgabenstellung müsset die Daten zuerst nach Kalenderwochen \"week\" \n# und Bedingungen \"condition\" zusammengefasst werden\n\ndf <- nova %>%\n    group_by(week, condit) %>%  \n    summarise(tot_sold = n()) \n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'week'. You can override using the\n`.groups` argument.\n```\n:::\n\n```{.r .cell-code}\n# überprüft die Voraussetzungen für einen t-Test\nggplot2::ggplot(df, aes(x = condit, y= tot_sold)) + # achtung 0 Punkt fehlt\n    geom_boxplot(fill = \"white\", color = \"black\", size = 1) + \n    labs(x=\"\\nBedingungen\", y=\"Durchschnittlich verkaufte Gerichte pro Woche\\n\") + \n    mytheme\n```\n\n::: {.cell-output-display}\n![](Statistik1_Loesung_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Auf den ersten Blick scheint es keine starken Abweichungen zu einer \n#Normalverteilung zu geben resp. es sind keine extremen schiefen Verteilungen\n# ersichtlich (vgl. Skript Statistik 2)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# führt einen t-Tests durch; \n# es wird angenommen, dass die Verkaufszahlen zwischen den Bedingungen \n# unabhängig sind\n\nt_test <- t.test(tot_sold ~ condit, data=df, var.equl = T)\n\n#alternative Formulierung\nt.test(df[df$condit == \"Basis\", ]$tot_sold, \n                 df[df$condit == \"Intervention\", ]$tot_sold) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  df[df$condit == \"Basis\", ]$tot_sold and df[df$condit == \"Intervention\", ]$tot_sold\nt = 0.27168, df = 9.9707, p-value = 0.7914\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -115.2743  147.2743\nsample estimates:\nmean of x mean of y \n     2203      2187 \n```\n:::\n:::\n\n\n## Methoden\n\nZiel war es die aggregierten Verkaufszahlen zwischen den Interventions- und Basiswochen zu vergleichen. Die Annahme ist, dass die wöchentlichen Verkaufszahlen unabhängig sind.  Daher können die Unterschiede zwischen den Verkaufszahlen pro Woche zwischen den beiden Bedingungen mittels t-Test geprüft werden. Obwohl die visuelle Inspektion keine schwerwiegenden Verletzungen der Modelvoraussetzung zeigte, wurde einen Welch t-Test gerechnet. Zudem muss gesagt werden, dass die Gruppengrösse hier jeweils mit n = 6 (Anzahl Wochen) eher klein ist. T-test liefern dennoch relativ reliable Resultate. Für mehr Infos dazu hier eine [Studie](https://scholarworks.umass.edu/cgi/viewcontent.cgi?article=1307&context=pare).\n\n## Ergebnisse\n\nIn den Basiswochen werden mehr Gerichte pro Woche verkauft als in den Interventionsowochen (siehe Abbildung 1). Die wöchentlichen Verkaufszahlen zwischen den Bedigungen (Basis oder Intervention) unterscheiden sich gemäss Welch t-Test jedoch nicht signifikant (*t*(10) = 0.272 , *p* = 0.791). Die Ergebnisse könnten mit einem $\\chi^2$-Test nochmals validiert werden, da die Gruppengrösse mit n = 6 doch eher klein ist.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Die wöchentlichen Verkaufszahlen für die Interventions- und Basiswochen unterscheiden sich nicht signifikant.](Statistik1_Loesung_files/figure-html/unnamed-chunk-7-1.png){width=80%}\n:::\n:::\n",
    "supporting": [
      "Statistik1_Loesung_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}